---

env:
  jobs:
    - ANSIBLE_VERSION='>=2.11,<2.12'

os:
  - linux
dist: focal

language: python
python:
  - 3.8

before_install:
  - sudo apt-get -q update
  - sudo apt-get install -y yamllint

install:
  - sudo pip install "ansible-core$ANSIBLE_VERSION"
  - sudo pip install ansible-lint
  - ansible-galaxy collection install community.general community.postgresql community.mysql

script:
  - >
    yamllint .
    && (echo 'YAML lint test: pass' && exit 0)
    || (echo 'YAML lint test: fail' && exit 1)
  - >
    ansible-lint -v tests/test.yml
    && (echo 'Ansible lint test: pass' && exit 0)
    || (echo 'Ansible lint test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
