---

- block:

  - name: FILE | Create systemd unit dir
    file:
      path: /etc/systemd/system/teleport.service.d
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: TEMPLATE | Prepare systemd unit
    template:
      src: systemd_override.conf.j2
      dest: /etc/systemd/system/teleport.service.d/override.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - reload systemd
      - restart teleport

  when: teleport_insecure

- name: Delete insecure systemd unit
  file:
    path: /etc/systemd/system/teleport.service.d
    state: absent
  notify:
    - reload systemd
    - restart teleport
  when: not teleport_insecure
