---

- name: ASSERT | Check the system use systemd
  assert:
    that: ansible_service_mgr == 'systemd'

- name: STAT | Check if teleport installed
  stat:
    path: "{{ teleport_bin_path }}"
  register: teleport_installed

- name: IMPORT_TASKS | Install
  import_tasks: install.yml
  when: not teleport_installed.stat.exists

- name: IMPORT_TASKS | Insecure
  import_tasks: insecure.yml

- name: TEMPLATE | Configure Teleport
  template:
    src: teleport.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: 0644
  notify: restart teleport

- name: SERVICE | Ensure Teleport is enabled on boot
  service:
    name: teleport
    enabled: true
